"""remove unused system config columns

Revision ID: 3c033e0c12d0
Revises: dcac96f38c22
Create Date: 2026-06-10 17:13:34.807128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3c033e0c12d0'
down_revision: Union[str, None] = 'dcac96f38c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Langgraph & Mem0 tables are maintained by their own schema builders
    op.alter_column('knowledge_base_chunks', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               comment='Embeddings from Ollama mxbai-large (1024)',
               existing_comment='Embeddings from Ollama (1024)',
               existing_nullable=True)
    op.drop_column('system_configs', 'telegram_bot_token')
    op.drop_column('system_configs', 'telegram_chat_id')
    op.drop_column('system_configs', 'storefront_api_token')
    op.drop_column('system_configs', 'webhook_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configs', sa.Column('webhook_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('system_configs', sa.Column('storefront_api_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('system_configs', sa.Column('telegram_chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('system_configs', sa.Column('telegram_bot_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('knowledge_base_chunks', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               comment='Embeddings from Ollama (1024)',
               existing_comment='Embeddings from Ollama mxbai-large (1024)',
               existing_nullable=True)
    # Langgraph & Mem0 tables are maintained by their own schema builders
    # ### end Alembic commands ###
