"""Add sender_id to Message

Revision ID: 9b729343f757
Revises: e0b61417aaf9
Create Date: 2026-06-22 23:07:04.059456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b729343f757'
down_revision: Union[str, None] = 'e0b61417aaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
