"""Add webhook_secret to system_configs

Revision ID: b49fc47a4511
Revises: 3c033e0c12d0
Create Date: 2026-06-10 23:55:29.710080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49fc47a4511'
down_revision: Union[str, None] = '3c033e0c12d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configs', sa.Column('webhook_secret', sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configs', 'webhook_secret')
    # ### end Alembic commands ###
