"""db_optimization_indexes

Revision ID: b8f891f53531
Revises: 9b729343f757
Create Date: 2026-06-23 15:09:01.407258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f891f53531'
down_revision: Union[str, None] = '9b729343f757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_assigned_user_id'), 'conversations', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_feedback_conversation_id'), 'feedback', ['conversation_id'], unique=False)
    op.create_index('ix_kb_chunk_embedding', 'knowledge_base_chunks', ['embedding_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.create_index(op.f('ix_knowledge_base_chunks_document_id'), 'knowledge_base_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index('ix_product_embedding_vector', 'product_embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.create_index(op.f('ix_product_embeddings_product_id'), 'product_embeddings', ['product_id'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_user_id'), 'tickets', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_conversation_id'), 'tickets', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_conversation_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_product_embeddings_product_id'), table_name='product_embeddings')
    op.drop_index('ix_product_embedding_vector', table_name='product_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_knowledge_base_chunks_document_id'), table_name='knowledge_base_chunks')
    op.drop_index('ix_kb_chunk_embedding', table_name='knowledge_base_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_feedback_conversation_id'), table_name='feedback')
    op.drop_index(op.f('ix_conversations_assigned_user_id'), table_name='conversations')
    # ### end Alembic commands ###
