"""Initial migration

Revision ID: ecd85b7e3e9f
Revises: 
Create Date: 2026-06-07 13:39:26.566012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'ecd85b7e3e9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_status', sa.String(length=50), server_default='pending', nullable=False, comment='pending | processing | completed | failed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), server_default='0.0000', nullable=False),
    sa.Column('peak_hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('csat_average', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_conversations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tickets', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('persona_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_name', sa.String(length=100), nullable=False),
    sa.Column('tone_of_voice', sa.String(length=100), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('out_of_context_message', sa.Text(), server_default='Maaf, saya asisten AI dari toko ini yang bertugas hanya untuk menjawab pertanyaan dengan konteks toko.', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=False),
    sa.Column('admin_api_token', sa.Text(), nullable=False),
    sa.Column('storefront_api_token', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('telegram_bot_token', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=False),
    sa.Column('operational_hours_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{"monday": {"start": "08:00", "end": "17:00"}}', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='admin or staff'),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('anonymous_customer_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active_ai', nullable=False, comment='active_ai | waiting_human | human_handling'),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(1024), nullable=True, comment='Embeddings from Ollama (1024)'),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_base_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False, comment='INFO | WARNING | CRITICAL'),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('workflow_step', sa.String(length=150), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('telegram_sent_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False, comment='CSAT rating 1-5'),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False, comment='customer | ai | staff'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='open', nullable=False, comment='open | in_progress | resolved'),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('messages')
    op.drop_table('feedback')
    op.drop_table('error_logs')
    op.drop_table('knowledge_base_chunks')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_table('persona_settings')
    op.drop_table('metric_snapshots')
    op.drop_table('knowledge_base_documents')
    # ### end Alembic commands ###
