"""Drop mem0 tables

Revision ID: f045fb665941
Revises: 4f2ae5561031
Create Date: 2026-06-14 10:13:09.525959

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f045fb665941'
down_revision: Union[str, None] = '4f2ae5561031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS mem0_memories_hnsw_idx")
    op.execute("DROP INDEX IF EXISTS mem0_memories_text_lemmatized_idx")
    op.execute("DROP TABLE IF EXISTS mem0_memories CASCADE")
    op.execute("DROP INDEX IF EXISTS mem0migrations_hnsw_idx")
    op.execute("DROP INDEX IF EXISTS mem0migrations_text_lemmatized_idx")
    op.execute("DROP TABLE IF EXISTS mem0migrations CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mem0migrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mem0migrations_pkey'))
    )
    op.create_index(op.f('mem0migrations_text_lemmatized_idx'), 'mem0migrations', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('mem0migrations_hnsw_idx'), 'mem0migrations', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('mem0_memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mem0_memories_pkey'))
    )
    op.create_index(op.f('mem0_memories_text_lemmatized_idx'), 'mem0_memories', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('mem0_memories_hnsw_idx'), 'mem0_memories', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
